[package]
name = "dagviz"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.6"
indexmap = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
derive_more = { version = "2.0.1", features = ["deref", "deref_mut"] }
